steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/scraper:latest || exit 0
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - '-t'
    - gcr.io/$PROJECT_ID/scraper:latest
    - '--cache-from'
    - gcr.io/$PROJECT_ID/scraper:latest
    - .
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - gcr.io/$PROJECT_ID/scraper:latest
- name: gcr.io/cloud-builders/gcloud
  args:
    - run
    - deploy
    - scraper
    - '--image'
    - gcr.io/$PROJECT_ID/scraper:latest
    - '--region'
    - us-central1
    - '--platform'
    - managed
images:
  - gcr.io/$PROJECT_ID/scraper:latest
